### ISSUE TITLE
Any idea if E2B can run in a silo?

### ISSUE THREAD

**Issue by CakeCrusher** [e2b-dev/code-interpreter#24] opened 2024-06-23 17:53 UTC
Based on the couple of minutes of reading on what E2B is it seems as if it's designed to be run on the cloud so I was curious to know if you can run it in a siled environment completely locally. By corollary meaning code interpreter can also run in a completely siloed environment. Correct?

If true then I'd love to integrate it into what we are building as a clone to OpenAIs code interpreter.
https://github.com/OpenGPTs-platform

**Comment by mlejva** [comment] 2024-07-08 19:32
Hey @CakeCrusher , you can't run E2B locally. To run E2B, you need a Linux machine with specific Kernel because we're using [micro VMs](https://github.com/firecracker-microvm/firecracker) instead of Docker containers for our sandboxes. 
Our plan is to first make it easy to self-host E2B on AWS and GCP accounts and then on general Linux machines

**Comment by ValentaTomas** [comment] 2024-07-22 21:50
Duplicate of https://github.com/e2b-dev/E2B/issues/239

**Closed by ValentaTomas** 2024-07-22 21:50 UTC
Labels: duplicate, feature, question
